baseURL = "https://jyst.co.uk"
title = "JYST"

[permalinks]
    post = "/blog/:slug"

[menu]

  [[menu.logo]]
    pre = "logo"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "RSVP"
    url = "/rsvp"
    weight = 10

  [[menu.main]]
    name = "LOCATION"
    url = "/location"
    weight = 20

  [[menu.main]]
    name = "DRESS CODE"
    url = "/dress"
    weight = 30

  [[menu.main]]
    name = "GIFTING"
    url = "/gifting"
    weight = 40

  [[menu.main]]
    name = "PHOTOS"
    url = "/photos"
    weight = 50

  [[menu.main]]
    name = "CONTACT"
    url = "/contact"
    weight = 60


[markup]
  [markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
  [markup.highlight]
    style = 'catppuccin-macchiato'
